In [6]:
import numpy as np

In [7]:
vetor = np.array([1, 2, 3, 4, 5, 6])

In [8]:
vetor

array([1, 2, 3, 4, 5, 6])

In [9]:
type(vetor)

numpy.ndarray

In [10]:
vetor2 = np.array([1, 2, 3, 4])

In [11]:
vetor2

array([1, 2, 3, 4])

In [ ]:
matrix = np.array([[10, 15, 20], [10, 20, 30],[10, 50, 60]], dtype= float)

In [ ]:
matrix

array([[10., 15., 20.],
       [10., 20., 30.],
       [10., 50., 60.]])

In [ ]:
#range(star, and, step), numero inicial, numero final sempre será -1, ex range(1, 20), para no 19 pois o 0 e o primeiro numero
a = range(1,20)

In [ ]:
type(a)

range

In [ ]:
a.start

1

In [ ]:
a.step

1

In [ ]:
a.stop

20

In [ ]:
list(range(1,21))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [ ]:
tuple(range(1, 21))#tuple e uma lista imutavel != de list que e completamente mutavel

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20)

In [ ]:
np.arange(1,21, 0.5)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5,
       12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. , 16.5, 17. ,
       17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5])

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros(shape = (5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(shape= (10, 10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
np.eye(5)#faz a mesma coisa que a identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.full(10, 5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [ ]:
np.full(shape= (10,5), fill_value= 5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [ ]:
np.empty((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
# _______________________inspecionando_array_________________

In [ ]:
vetor= np.array([10, 15, 20, 30])

In [ ]:
vetor.shape

(4,)

In [ ]:
len(vetor)

4

In [ ]:

vetor.ndim

1

In [ ]:
vetor.size

4

In [ ]:
vetor.dtype

dtype('int64')

In [ ]:
vetor= np.array([10, 15, 30], dtype = float)#formatacao da array

In [ ]:
vetor

array([10., 15., 30.])

In [ ]:
vetor.dtype

dtype('float64')

In [ ]:
vetor.astype(int)#conversao do vetor.

array([10, 15, 30])

In [ ]:
vetor.dtype

dtype('float64')

In [ ]:
#___________________,_______operacao_matematicas__________________

In [ ]:
vetor1 = np.array([2, 4, 6])
vetor2 = np.array([1, 3, 5])

In [ ]:
soma = vetor1+vetor2 #soma os 2 vetores, coluna+coluna, operacoes sempre seguirao este fluxo

In [ ]:
soma

array([ 3,  7, 11])

In [ ]:
soma = np.add(vetor1, vetor2) #soma na lib numpy

In [ ]:
soma

array([ 3,  7, 11])

In [ ]:
sub = vetor1-vetor2 #fluxo de operacao matematica continua coluna 'x' coluna

In [ ]:
sub

array([1, 1, 1])

In [ ]:
np.subtract(vetor1, vetor2)#comando numpy

array([1, 1, 1])

In [ ]:
div = vetor1/vetor2

In [ ]:
div

array([2.        , 1.33333333, 1.2       ])

In [ ]:
np.divide(vetor1, vetor2)

array([2.        , 1.33333333, 1.2       ])

In [ ]:
mult = vetor1*vetor2

In [ ]:
mult

array([ 2, 12, 30])

In [ ]:
np.multiply(vetor1, vetor2)

array([ 2, 12, 30])

In [ ]:
vetor1+1#adiciona 1 cordenada em cada contante dentro do vetor, funciona para todas as operacoes do mesmo modo

array([3, 5, 7])

In [ ]:
v = vetor1**2

In [ ]:
v

array([ 4, 16, 36])

In [ ]:
np.sqrt(v)#raiz quadrada de cada cordenada.

array([2., 4., 6.])

In [ ]:
np.sin(vetor1)

array([ 0.90929743, -0.7568025 , -0.2794155 ])

In [ ]:
np.log2(v)

array([2.      , 4.      , 5.169925])

In [12]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]]) 

In [ ]:
matrix.shape

(3, 3)

In [ ]:
matrix1.shape

(2, 2)

In [ ]:
matrix1.ndim

2

In [13]:
matrix1+matrix2 #para somar as matrizes

array([[ 6,  8],
       [10, 12]])

In [14]:
(4)*matrix1 #multiplicando por 4 cordenada por cordenada

array([[ 4,  8],
       [12, 16]])

In [15]:
np.dot(matrix1, matrix2) #produto matricial da matrix1 e matrix2

array([[19, 22],
       [43, 50]])

In [16]:
matrix1.dot(matrix2) #maneira diferente de realizar o produto da matrix1 pela matrix2.

array([[19, 22],
       [43, 50]])

In [17]:
#____________________________________comparacoes__logicas_________________
a = np.array([10, 15, 20])
b = np.array([10, 18, 21])

In [18]:
a == b #cordenadas comparativas elemento a elemento

array([ True, False, False])

In [19]:
a != b

array([False,  True,  True])

In [20]:
a > b

array([False, False, False])

In [21]:
a < b

array([False,  True,  True])

In [22]:
a <= b

array([ True,  True,  True])

In [23]:
a >= b

array([ True, False, False])

In [24]:
a = np.array([1, 1, 1])
b = np.array([1, 1, 1])

In [25]:
np.array_equal(a, b) #compara todos os elemento de um vetor

True

In [ ]:
#______________________________funcoes_de_agregacao_________________________________


In [26]:
vetor = np.arange(1, 21)

In [27]:
vetor

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [28]:
vetor.sum() #soma de tod #s os elementos dento do vetor

210

In [29]:
sum(vetor) #funcao built-in para somar todos os elementos do vetor

210

In [30]:
vetor.max()# valor maximo do vetor

20

In [31]:
max(vetor)

20

In [32]:
vetor.min() #menor elemento do vetor

1

In [33]:
min(vetor)#built-in

1

In [34]:
vetor.mean() #mediana do vetor

10.5

In [35]:
np.median(vetor)#numpy funcao para media do vetor

10.5

In [36]:
np.std(vetor)#para desvio padrao dos numeros do vetor

5.766281297335398

In [37]:
np.var(vetor)#variancia do vetor

33.25

In [38]:
matrix = np.array([[10, 5, 19], [5, 25, 32], [50, 9, 12]])

In [39]:
matrix

array([[10,  5, 19],
       [ 5, 25, 32],
       [50,  9, 12]])

In [41]:
np.corrcoef(matrix) #calcular coeficiente de correlacao da matrix

array([[ 1.        ,  0.40405541, -0.09764964],
       [ 0.40405541,  1.        , -0.94981873],
       [-0.09764964, -0.94981873,  1.        ]])

In [42]:
#__________________________ordenando__array___________________


In [43]:
vetor = np.array([25, 1, 33, -10])

In [44]:
vetor.sort()#ordena o vetor de modo sequencial do < para >

In [45]:
vetor

array([-10,   1,  25,  33])

Subsetting, Slicing, Indexing

In [47]:
vetor1 = np.array([1, 2, 3]) #indexacao e a mesma do build-in


In [49]:
vetor1[2]
vetor1[0]

1

In [50]:
matrix = np.array ([[1, 2, 3], [4, 5, 6]])

In [51]:
matrix[1]

array([4, 5, 6])

In [52]:
matrix[1, 2] #pARA selecionar elementos especificos da matrix

6

In [53]:
vetor1[0:1] #slicing de um array, sendo o ending exclusivo

array([1])

In [54]:
vetor1[0:2]

array([1, 2])

In [56]:
matrix[0:2, 1] #metodo para selecionar itens especificos de uma matrix

array([2, 5])

In [57]:
matrix[:, 1]# metodo diferente para selecionar elementos dentro de uma matrix

array([2, 5])

In [58]:
vetor1[::-1] #seleciona itens do vetor e inverte as posicoes

array([3, 2, 1])

In [60]:
vetor1 [-1] #seleciona itens de maneira negativa (de tras para frente) de um vetor

3

In [61]:
vetor1[vetor1<2] #comparativos de elementos booleanos.

array([1])

In [62]:
vetor1[vetor1 >=2] 

array([2, 3])

In [63]:
vetor3 = np.arange(1, 101)

In [64]:
vetor3[vetor3>= 50]

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [65]:
vetor4 = np.random.randint(1, 50, 50) #criando um vetor random de ate 50 numeros.

In [66]:
vetor4


array([38, 13, 37, 25, 32, 11,  5, 39, 41, 25, 17, 27,  6, 10, 46,  9, 14,
       42, 17, 29, 34, 36, 22, 13,  4,  7, 45, 20, 24,  3, 42, 18, 32, 30,
       16, 32, 27, 26, 26, 34, 49, 17, 21,  1, 30, 42, 21, 16, 11, 15])

In [67]:
vetor4[vetor4 > 25]

array([38, 37, 32, 39, 41, 27, 46, 42, 29, 34, 36, 45, 42, 32, 30, 32, 27,
       26, 26, 34, 49, 30, 42])